const settings = {
    player: undefined,
    platformY: undefined,
    enemyY: undefined,
    currentPlayerFace: "default",
    startGenerationPlatforms: true,
    startGenerationEnemies: true,
    enemyDisabled: false,
    now: undefined,
    then: performance.now(),
    delta: 0,
    lastFrameTime: 0,
    LEFT: false,
    RIGHT: false,
    gravity: 0.6,
    score: undefined,
    highScore: 0,
    lastIndex: undefined,
    audioEnabled: true,
    musicEnabled: true,
    gamePaused: false,
    platforms: [],
    enemies: [],
    clouds: [],
    gameOver: false,
    generateEnemies: false,
    generatePlatforms: false,
};
export default settings;
