export const settings = {
    player: undefined,
    platformY: undefined,
    enemyY: undefined,
    currentPlayerFace: "default",
    startGenerationPlatforms: true,
    startGenerationEnemies: true,
    enemyDisabled: false,
    now: undefined,
    then: performance.now(),
    delta: undefined,
    LEFT: false,
    RIGHT: false,
    gravity: 1,
    score: undefined,
    highScore: 0,
    lastIndex: undefined,
    audioEnabled: true,
    musicEnabled: true,
    gamePaused: false,
    platforms: [],
    enemies: [],
    clouds: [],
};